### ISSUE TITLE
gnu tests fail with DEBUG=TRUE

### ISSUE THREAD

**Issue by mnlevy1981** [ESCOMP/WW3-CESM#3]
### Description of the issue:

When I set `DEBUG=TRUE`, the model crashes with the following error:

```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x2ac3ccd7494f in ???
#1  0xabaefc in __wav_comp_mct_MOD_wav_run_mct
        at /glade/work/mlevy/codes/CESM/cesm2_2_beta05/components/ww3/src/cpl_mct/wav_comp_mct.F90:761
#2  0x42767b in __component_mod_MOD_component_run
        at /glade/work/mlevy/codes/CESM/cesm2_2_beta05/cime/src/drivers/mct/main/component_mod.F90:714
#3  0x410ab7 in __cime_comp_mod_MOD_cime_run
        at /glade/work/mlevy/codes/CESM/cesm2_2_beta05/cime/src/drivers/mct/main/cime_comp_mod.F90:2651
#4  0x426156 in cime_driver
        at /glade/work/mlevy/codes/CESM/cesm2_2_beta05/cime/src/drivers/mct/main/cime_driver.F90:133
#5  0x426262 in main
        at /glade/work/mlevy/codes/CESM/cesm2_2_beta05/cime/src/drivers/mct/main/cime_driver.F90:23
```

### Version:
- CESM: `cesm2_2_beta05`
- WW3: `ww3_190402`

### Machine/Environment Description:

I was running `aux_pop_MARBL` on cheyenne, and every `_D` test failed with `gnu` (`intel` was fine)

### Any xml/namelist changes or SourceMods:

Nope

**Comment by fischer-ncar** [comment]
Ran into this problem with a couple of tests for WW3 and CTSM.

Bill looked into it and said this.

```
In both cases there is logic that assumes that Fortran uses short-circuiting, 
whereas in fact that is not part of the Fortran standard, even though many 
compilers do it. I guess earlier gfortran versions did it, whereas 9.1 doesn't. 

For the G compset, the problem is on this line of wav_comp_mct:

      if (outfreq .gt. 0 .and. mod(hh, outfreq) .eq. 0 ) then

Again, if outfreq == 0, the mod may still be evaluated, leading to divide by 0.
```

**Comment by mnlevy1981** [comment]
I have a branch with a potential fix on it; I want to run a few more tests, but I'll submit a PR early next week.
